In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [16]:
df_train = pd.read_csv('train_landmark_features.csv')
df_test = pd.read_csv('test_landmark_features.csv')

In [17]:
df_train.head()

,D1,D2,D3,D4,D5,D6,D7,R1,R2,R3,...,R5,R6,R7,R8,R9,R10,angle1,angle2,angle3,label
0,128.003906,113.357840,167.191507,68.410526,109.000000,64.000000,34.000000,0.885581,0.765612,0.678012,...,0.587156,1.068914,0.499985,0.961557,0.627620,0.531250,63.628011,49.382405,74.058074,Heart
1,120.813906,106.531685,158.675770,65.192024,103.392456,59.211485,31.144823,0.881783,0.761388,0.671380,...,0.572687,1.101003,0.490105,0.970532,0.630530,0.525993,62.128981,49.194443,74.853016,Heart
2,124.004032,110.004545,162.003086,67.201190,106.000000,61.008196,32.000000,0.887105,0.765442,0.679027,...,0.575549,1.101511,0.491986,0.963597,0.633973,0.524520,65.341778,53.117471,74.711467,Heart
3,124.402572,107.056060,162.788206,65.192024,106.301458,60.074953,31.064449,0.860561,0.764199,0.657640,...,0.565138,1.085178,0.482908,0.992951,0.613275,0.517095,62.558041,51.888258,75.073994,Heart
4,125.574679,107.280007,163.884105,64.637450,106.606754,58.189346,30.675723,0.854312,0.766241,0.654609,...,0.545832,1.110812,0.463384,0.993724,0.606317,0.527171,60.392727,51.585160,74.548410,Heart

In [18]:
X_train = df_train.iloc[:,:-1]
X_test = df_test.iloc[:,:-1]
y_train = df_train.iloc[:,-1]
y_test = df_test.iloc[:,-1]

In [19]:
X_train.head()

,D1,D2,D3,D4,D5,D6,D7,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,angle1,angle2,angle3
0,128.003906,113.357840,167.191507,68.410526,109.000000,64.000000,34.000000,0.885581,0.765612,0.678012,1.174348,0.587156,1.068914,0.499985,0.961557,0.627620,0.531250,63.628011,49.382405,74.058074
1,120.813906,106.531685,158.675770,65.192024,103.392456,59.211485,31.144823,0.881783,0.761388,0.671380,1.168498,0.572687,1.101003,0.490105,0.970532,0.630530,0.525993,62.128981,49.194443,74.853016
2,124.004032,110.004545,162.003086,67.201190,106.000000,61.008196,32.000000,0.887105,0.765442,0.679027,1.169849,0.575549,1.101511,0.491986,0.963597,0.633973,0.524520,65.341778,53.117471,74.711467
3,124.402572,107.056060,162.788206,65.192024,106.301458,60.074953,31.064449,0.860561,0.764199,0.657640,1.170281,0.565138,1.085178,0.482908,0.992951,0.613275,0.517095,62.558041,51.888258,75.073994
4,125.574679,107.280007,163.884105,64.637450,106.606754,58.189346,30.675723,0.854312,0.766241,0.654609,1.177924,0.545832,1.110812,0.463384,0.993724,0.606317,0.527171,60.392727,51.585160,74.548410

In [20]:
X_test.head()

,D1,D2,D3,D4,D5,D6,D7,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,angle1,angle2,angle3
0,117.004273,97.046381,162.111073,63.253458,99.020200,57.035077,30.016662,0.829426,0.721754,0.598641,1.181620,0.575994,1.109027,0.487461,1.020339,0.638793,0.526284,61.313852,48.653230,73.321098
1,121.696343,110.222502,152.839785,64.443774,103.585713,58.309519,30.149627,0.905717,0.796235,0.721164,1.174837,0.562911,1.105202,0.479139,0.939787,0.622130,0.517062,67.830416,54.153963,75.252129
2,113.441615,99.080775,151.330764,58.898217,98.325988,56.222771,29.154759,0.873408,0.749627,0.654730,1.153730,0.571800,1.047587,0.495610,0.992382,0.599010,0.518558,65.488134,53.609656,75.780404
3,126.435754,107.786827,170.425937,67.896981,110.168053,62.801274,33.376639,0.852503,0.741881,0.632456,1.147663,0.570050,1.081140,0.496705,1.022092,0.616304,0.531464,65.589467,53.610403,76.458105
4,148.165448,133.540256,184.328511,77.175126,125.099960,73.061618,39.051248,0.901291,0.803812,0.724469,1.184376,0.584026,1.056302,0.493108,0.936796,0.616908,0.534497,69.053212,55.360378,72.852703

In [21]:
from sklearn.preprocessing import StandardScaler

# Inisialisasi StandardScaler
scaler = StandardScaler()

# Fit scaler pada X_train dan transform
X_train_scaled = scaler.fit_transform(X_train)

# Transform X_test dengan scaler yang sudah di-fit dari X_train
X_test_scaled = scaler.transform(X_test)

In [22]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# Definisikan rentang parameter untuk SVM
param_grid = {
    'C': [0.1, 1, 10, 100, 1000],
    'kernel': ['rbf'],
    'gamma': ['scale', 'auto', 1, 0.1, 0.01, 0.001],
}

# Inisialisasi model SVM
svc = SVC(probability=True)


# Set up GridSearchCV dengan cross-validation 5-fold
grid_search = GridSearchCV(estimator=svc, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)

# Fit grid search pada data training
grid_search.fit(X_train_scaled, y_train)

# Menampilkan hasil terbaik
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation score: ", grid_search.best_score_)

# Menggunakan model terbaik untuk prediksi pada data testing
best_svc = grid_search.best_estimator_
y_pred = best_svc.predict(X_test_scaled)

# Evaluasi akurasi model
from sklearn.metrics import accuracy_score
print("Test set accuracy: ", accuracy_score(y_test, y_pred))

Fitting 5 folds for each of 30 candidates, totalling 150 fits
Best parameters found:  {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}
Best cross-validation score:  0.532004696576443
Test set accuracy:  0.5732323232323232

In [23]:
import joblib

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # Fit dan transform data training

# Simpan scaler ke file
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

In [24]:


# Simpan model ke file
joblib.dump(best_svc, 'best_svc_model.pkl')

print("Model berhasil disimpan!")

Model berhasil disimpan!