In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df_train = pd.read_csv('train_landmark_features.csv')
df_test = pd.read_csv('test_landmark_features.csv')

In [3]:
df_train.head()

,D1,D2,D3,D4,D5,D6,D7,R1,R2,R3,...,R5,R6,R7,R8,R9,R10,angle1,angle2,angle3,label
0,117.004273,97.046381,162.111073,63.253458,99.020200,57.035077,30.016662,0.829426,0.721754,0.598641,...,0.575994,1.109027,0.487461,1.020339,0.638793,0.526284,61.313852,48.653230,73.321098,Heart
1,126.063476,107.000000,164.012195,67.801180,108.041659,61.008196,32.015621,0.848779,0.768623,0.652391,...,0.564673,1.111345,0.483948,1.009735,0.627547,0.524776,66.394145,53.490772,74.554702,Heart
2,126.015872,107.018690,174.025860,66.610810,108.018517,61.032778,31.016125,0.849248,0.724122,0.614959,...,0.565021,1.091394,0.484326,1.009343,0.616661,0.508188,63.995346,53.174587,73.835501,Heart
3,124.486947,109.178753,162.003086,67.230945,105.475116,60.299254,32.140317,0.877030,0.768423,0.673930,...,0.571692,1.114955,0.484382,0.966077,0.637410,0.533014,66.266727,53.241626,74.513375,Heart
4,127.000000,112.040171,157.003185,66.850580,108.004630,60.000000,32.000000,0.882206,0.808901,0.713617,...,0.555532,1.114176,0.472441,0.963981,0.618960,0.533333,66.884087,54.994116,74.744881,Heart

In [4]:
X_train = df_train.iloc[:,:-1]
X_test = df_test.iloc[:,:-1]
y_train = df_train.iloc[:,-1]
y_test = df_test.iloc[:,-1]

In [5]:
X_train.head()

,D1,D2,D3,D4,D5,D6,D7,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,angle1,angle2,angle3
0,117.004273,97.046381,162.111073,63.253458,99.020200,57.035077,30.016662,0.829426,0.721754,0.598641,1.181620,0.575994,1.109027,0.487461,1.020339,0.638793,0.526284,61.313852,48.653230,73.321098
1,126.063476,107.000000,164.012195,67.801180,108.041659,61.008196,32.015621,0.848779,0.768623,0.652391,1.166804,0.564673,1.111345,0.483948,1.009735,0.627547,0.524776,66.394145,53.490772,74.554702
2,126.015872,107.018690,174.025860,66.610810,108.018517,61.032778,31.016125,0.849248,0.724122,0.614959,1.166614,0.565021,1.091394,0.484326,1.009343,0.616661,0.508188,63.995346,53.174587,73.835501
3,124.486947,109.178753,162.003086,67.230945,105.475116,60.299254,32.140317,0.877030,0.768423,0.673930,1.180249,0.571692,1.114955,0.484382,0.966077,0.637410,0.533014,66.266727,53.241626,74.513375
4,127.000000,112.040171,157.003185,66.850580,108.004630,60.000000,32.000000,0.882206,0.808901,0.713617,1.175876,0.555532,1.114176,0.472441,0.963981,0.618960,0.533333,66.884087,54.994116,74.744881

In [6]:
X_test.head()

,D1,D2,D3,D4,D5,D6,D7,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,angle1,angle2,angle3
0,128.003906,113.357840,167.191507,68.410526,109.000000,64.000000,34.000000,0.885581,0.765612,0.678012,1.174348,0.587156,1.068914,0.499985,0.961557,0.627620,0.531250,63.628011,49.382405,74.058074
1,121.103262,104.000000,155.029030,62.625873,103.077641,58.034473,31.016125,0.858771,0.781165,0.670842,1.174874,0.563017,1.079115,0.479215,0.991131,0.607560,0.534443,64.543761,52.591886,73.597509
2,121.037184,106.042444,154.003247,62.201286,104.019229,59.008474,31.000000,0.876115,0.785939,0.688573,1.163604,0.567284,1.054108,0.487524,0.980921,0.597979,0.525348,65.482413,53.126514,74.543491
3,124.257797,114.017543,158.154987,64.815122,107.168092,62.128898,33.060551,0.917589,0.785671,0.720923,1.159466,0.579733,1.043236,0.500000,0.939926,0.604799,0.532128,67.519868,54.429185,76.300634
4,125.035995,106.075445,166.000000,68.249542,108.018517,61.000000,33.000000,0.848359,0.753229,0.639009,1.157542,0.564718,1.118845,0.487860,1.018318,0.631832,0.540984,63.434949,50.946863,75.384645

In [7]:
from sklearn.preprocessing import StandardScaler

# Inisialisasi StandardScaler
scaler = StandardScaler()

# Fit scaler pada X_train dan transform
X_train_scaled = scaler.fit_transform(X_train)

# Transform X_test dengan scaler yang sudah di-fit dari X_train
X_test_scaled = scaler.transform(X_test)

In [8]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# Definisikan rentang parameter untuk SVM
param_grid = {
    'C': [0.1, 1, 10, 100, 1000],
    'kernel': ['rbf'],
    'gamma': ['scale', 'auto', 1, 0.1, 0.01, 0.001],
}

# Inisialisasi model SVM
svc = SVC()

# Set up GridSearchCV dengan cross-validation 5-fold
grid_search = GridSearchCV(estimator=svc, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)

# Fit grid search pada data training
grid_search.fit(X_train_scaled, y_train)

# Menampilkan hasil terbaik
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation score: ", grid_search.best_score_)

# Menggunakan model terbaik untuk prediksi pada data testing
best_svc = grid_search.best_estimator_
y_pred = best_svc.predict(X_test_scaled)

# Evaluasi akurasi model
from sklearn.metrics import accuracy_score
print("Test set accuracy: ", accuracy_score(y_test, y_pred))

Fitting 5 folds for each of 30 candidates, totalling 150 fits
Best parameters found:  {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}
Best cross-validation score:  0.5476959447172213
Test set accuracy:  0.5655430711610487